name: Build options.json

run-name: Build options.json for ${{ inputs.path }}

on:
  workflow_call:
    inputs:
      repository:
        type: string
      ref:
        type: string
      path:
        type: string
      doc-dir:
        type: string
      file:
        type: string
      attribute:
        type: string
      runs-on:
        type: string

jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v5
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          path: ${{ inputs.path }}

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Build options.json for ${{ inputs.path }}
        run: |
          mkdir -p site/${{ inputs.doc-dir }}
          cd ${{ inputs.path }}
          git rev-parse HEAD > ../site/${{ inputs.doc-dir }}/revision
          nix-build ${{ inputs.file }} -A ${{ inputs.attribute }}
          cp result/share/doc/${{ inputs.doc-dir }}/options.json{,.br} ../site/${{ inputs.doc-dir }}/

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.doc-dir }}
          path: site
