name: Update flake inputs
on:
  schedule:
    - cron: "38 10 * * 0,3"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Nix Quick Install
        uses: nixbuild/nix-quick-install-action@v30
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v24
